name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

concurrency:
  group: "teahouse"
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: teahouse
      url: https://example.teahouse.page
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Upload
      uses: teahouse-hosting/upload@trunk
      with:
        domain: stealthiswebsite.art
        root: .
    - name: Upload WWW
      uses: teahouse-hosting/upload@trunk
      with:
        domain: www.stealthiswebsite.art
        root: .
